from typing import List

from app.models import Skill


# Сгенерировано convert_skills.py — дальше можно править вручную
SKILLS: List[Skill] = [
    Skill(name="Администрирование", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Азартные игры", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Акваланг/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Акробатика", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Алхимия/ТУ", base_attr="IQ", difficulty="VH", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine", "science"], base_weight=2),
    Skill(name="Анализ разведданных/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Анализ рынка", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Антропология", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Арбалет", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["ranged_primitive"], base_weight=1),
    Skill(name="Артиллерия/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Артистизм", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Археология", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Архитектура/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Астрономия/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["science"], base_weight=2),
    Skill(name="Аэробатика", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Бег", base_attr="HT", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Биоинженерия/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["science"], base_weight=2),
    Skill(name="Биология/ТУ", base_attr="IQ", difficulty="VH", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine"], base_weight=1),
    Skill(name="Боевой скафандр/ ТУ", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=8, max_tl=12, points=0, categories=["protective_suit"], base_weight=1),
    Skill(name="Бой вслепую", base_attr="Per", difficulty="VH", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Бокс", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Болас", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Борьба", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_unarmed"], base_weight=3),
    Skill(name="Борьба сумо", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_unarmed"], base_weight=3),
    Skill(name="Бухгалтерский учет", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Быстрое выхватывание", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Быстрое чтение", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Велосипед", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Верховая езда", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Ветеринария/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine"], base_weight=1),
    Skill(name="Взлом сознания/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["stealth"], base_weight=1),
    Skill(name="Взлом/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["stealth"], base_weight=1),
    Skill(name="Взрывные работы/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Внушение", base_attr="Will", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Внушение эмоций", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Водолазный костюм/ТУ", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Вождение/ТУ", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["vehicle"], base_weight=1),
    Skill(name="Воздействие музыкой", base_attr="IQ", difficulty="VH", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Врачебное дело/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine"], base_weight=1),
    Skill(name="Выбивание дверей", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Выживание", base_attr="Per", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["survival"], base_weight=1),
    Skill(name="Выживание в городе", base_attr="Per", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["survival"], base_weight=1),
    Skill(name="Выступление", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Вязание узлов", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="География/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["science"], base_weight=2),
    Skill(name="Геология/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["science"], base_weight=2),
    Skill(name="Геологоразведка/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Геральдика", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Гипноз", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Глотание огня", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Грим/ТУ", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Групповое выступление", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Дага", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Двуручный меч", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Двуручный топор/булава", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Двуручный цеп", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Дзен-лучник", base_attr="IQ", difficulty="VH", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Дзитте/Сай", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_unarmed"], base_weight=3),
    Skill(name="Дзюдо", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_unarmed"], base_weight=3),
    Skill(name="Диагностика/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine"], base_weight=1),
    Skill(name="Дипломатия", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Домашнее хозяйство", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Допрос", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Драка", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_unarmed"], base_weight=3),
    Skill(name="Древковое оружие", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Духовая трубка", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["ranged_primitive"], base_weight=1),
    Skill(name="Заговаривание зубов", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Запугивание", base_attr="Will", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Знание местности", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Знание улиц", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Знаток", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Знахарь/ТУ", base_attr="IQ", difficulty="VH", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Игры", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Изменение внешности/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Изобразительное искусство", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Инженерия/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["science"], base_weight=2),
    Skill(name="Искусство метания", base_attr="DX", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Искусство невидимости", base_attr="IQ", difficulty="VH", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Использование компьютера/ТУ", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=7, max_tl=12, points=0, categories=["computer"], base_weight=2),
    Skill(name="Использование электроники/ ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["electronics"], base_weight=2),
    Skill(name="Исследования/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="История", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Каменщик", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Каратэ", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_unarmed"], base_weight=3),
    Skill(name="Карманное воровство", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["stealth"], base_weight=1),
    Skill(name="Картография/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Киай", base_attr="HT", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Кнут", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Кожевник", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Композитор", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Компьютерный взлом/ТУ", base_attr="IQ", difficulty="VH", tags=["mundane"], min_tl=7, max_tl=12, points=0, categories=["computer", "stealth"], base_weight=2),
    Skill(name="Контрабанда", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Контроль тела", base_attr="HT", difficulty="VH", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Коньки", base_attr="HT", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Копье", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Копьеметалка", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade", "ranged_primitive"], base_weight=3),
    Skill(name="Кораблевождение/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["vehicle"], base_weight=1),
    Skill(name="Короткий меч", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Космический скафандр/ТУ", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=8, max_tl=12, points=0, categories=["protective_suit"], base_weight=1),
    Skill(name="Космонавт/ТУ", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Костюм химзащиты/ТУ", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=8, max_tl=12, points=0, categories=["protective_suit"], base_weight=1),
    Skill(name="Кража", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["stealth"], base_weight=1),
    Skill(name="Криминология/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Криптография/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Кузнец/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Кусари", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Кучер", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Лазание", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Лассо", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["ranged_primitive"], base_weight=1),
    Skill(name="Легкий шаг", base_attr="DX", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Летчик", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["vehicle"], base_weight=1),
    Skill(name="Лидерство", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Лингвистика", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Литература", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Ловкость рук", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["stealth"], base_weight=1),
    Skill(name="Ловушки/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Лук", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["ranged_primitive"], base_weight=1),
    Skill(name="Лучевое оружие/ТУ", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=9, max_tl=12, points=0, categories=["firearms_hi_tech"], base_weight=1),
    Skill(name="Лыжный спорт", base_attr="HT", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Малые корабли/ТУ", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["vehicle"], base_weight=1),
    Skill(name="Малый меч", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Маскировка", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["stealth"], base_weight=1),
    Skill(name="Математика/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["science"], base_weight=2),
    Skill(name="Машинопись", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Медитация", base_attr="Will", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Ментальная сила", base_attr="IQ", difficulty="E", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Ментальный блок", base_attr="Will", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Металлургия/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["science"], base_weight=2),
    Skill(name="Метание", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Метательное оружие", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Метеорология/ ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Механик/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Мономолекулярный кнут", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=9, max_tl=12, points=0, categories=["firearms_hi_tech"], base_weight=1),
    Skill(name="Моряк/ТУ", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Мощный удар", base_attr="Will", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Музыкальный инструмент", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Наблюдатель", base_attr="Per", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Навигация/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Наводчик/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Навьючивание", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Натуралист", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["survival"], base_weight=1),
    Skill(name="Недвижимая стойка", base_attr="DX", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Нетрадиционная медицина", base_attr="Per", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Нож", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Обращение с животными", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Обучение", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Обыск", base_attr="Per", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Огнестрельное оружие/ТУ", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=4, max_tl=12, points=0, categories=["firearms"], base_weight=3),
    Skill(name="Оккультизм", base_attr="IQ", difficulty="A", tags=["supernatural"], min_tl=0, max_tl=8, points=0, categories=["magic"], base_weight=1),
    Skill(name="Определение лжи", base_attr="Per", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Оружейник/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Отбрасывание", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Очарование", base_attr="Will", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Палаш", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Палеонтология/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Парализующий удар", base_attr="IQ", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Парашют/ТУ", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Парирование метательного оружия", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Парящий прыжок", base_attr="IQ", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Пение", base_attr="HT", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Первая помощь/ ТУ", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Пика", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Пилотирование/ ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["vehicle"], base_weight=1),
    Skill(name="Пирушки", base_attr="HT", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Письмо", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Плавание", base_attr="HT", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Плащ", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Плотник", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Побег", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Повар", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Погрузка/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Подводная акробатика", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Подводная лодка/ ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["vehicle"], base_weight=1),
    Skill(name="Подводник/ТУ", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["vehicle"], base_weight=1),
    Skill(name="Подделка/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Подражание звукам", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Полет", base_attr="HT", difficulty="A", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["vehicle"], base_weight=1),
    Skill(name="Политика", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Попрошайничество", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Посох", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Поэзия", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Право", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Праща", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["ranged_primitive"], base_weight=1),
    Skill(name="Предсказание погоды", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Предсказание судьбы", base_attr="IQ", difficulty="A", tags=["supernatural"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Природная атака", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Программирование/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=7, max_tl=12, points=0, categories=["computer"], base_weight=2),
    Skill(name="Промывка сознания/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Пропаганда/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Профессиональные навыки", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Прыжки", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Психология", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine"], base_weight=1),
    Skill(name="Публичное выступление", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Работа с опасными материалами/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Рапира", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Распылители/ТУ", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=4, max_tl=12, points=0, categories=["firearms"], base_weight=3),
    Skill(name="Религиозный обряд", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine"], base_weight=1),
    Skill(name="Ремонт электроники/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["electronics"], base_weight=2),
    Skill(name="Рисование символов", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Ритуальная магия", base_attr="IQ", difficulty="VH", tags=["supernatural"], min_tl=0, max_tl=8, points=0, categories=["magic"], base_weight=1),
    Skill(name="Рыбная ловля", base_attr="Per", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["survival"], base_weight=1),
    Skill(name="Сабля", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Садовод", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["survival"], base_weight=1),
    Skill(name="Самогипноз", base_attr="Will", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Сбрасывание", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Свежие новости/ТУ", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Свободное падение", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Сексапильность", base_attr="HT", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Сельское хозяйство/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["survival"], base_weight=1),
    Skill(name="Сеть", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Силовой кнут", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=9, max_tl=12, points=0, categories=["firearms_hi_tech"], base_weight=1),
    Skill(name="Силовой меч", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=9, max_tl=12, points=0, categories=["melee_blade", "firearms_hi_tech"], base_weight=3),
    Skill(name="Скакун", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Скафандр/ТУ", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=8, max_tl=12, points=0, categories=["protective_suit"], base_weight=1),
    Skill(name="Скрытность", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["stealth"], base_weight=1),
    Skill(name="Следопыт", base_attr="Per", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["survival"], base_weight=1),
    Skill(name="Слежка", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Слесарь/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Смертельный удар", base_attr="IQ", difficulty="VH", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Собирание", base_attr="Per", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Соколиная охота", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["survival"], base_weight=1),
    Skill(name="Сокрушительный удар", base_attr="IQ", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Солдат/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Социология", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Спорт", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Странная наука", base_attr="IQ", difficulty="VH", tags=["supernatural"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Стратегия", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Судебная экспертиза/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Сценический бой", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Тайное знание", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Тактика", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Танцы", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Тауматология", base_attr="IQ", difficulty="VH", tags=["supernatural"], min_tl=0, max_tl=8, points=0, categories=["magic"], base_weight=1),
    Skill(name="Теология", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Тонфа", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Топор/Булава", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Торговое дело", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Тяжелая атлетика", base_attr="HT", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Тяжелое оружие/ТУ", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=4, max_tl=12, points=0, categories=["firearms"], base_weight=3),
    Skill(name="Убеждение", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Увлечение", base_attr="Will", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Удавка", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Управление дыханием", base_attr="HT", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Утаивание", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Фальшивомонетчик/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Фармакология/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine"], base_weight=1),
    Skill(name="Физика/ТУ", base_attr="IQ", difficulty="VH", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["science"], base_weight=2),
    Skill(name="Физиология/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine"], base_weight=1),
    Skill(name="Философия", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Финансы", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Фотографирование/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Химия/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["science"], base_weight=2),
    Skill(name="Хирургия/ТУ", base_attr="IQ", difficulty="VH", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine"], base_weight=1),
    Skill(name="Хобби", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Ходьба", base_attr="HT", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Хорошие манеры", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["social"], base_weight=1),
    Skill(name="Цеп", base_attr="DX", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=["melee_blade"], base_weight=3),
    Skill(name="Член экипажа/ТУ", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Чревовещание", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Чтение по губам", base_attr="Per", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Чувство тела", base_attr="DX", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Шитье/ТУ", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Щит", base_attr="DX", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Экзорцизм", base_attr="Will", difficulty="H", tags=["supernatural"], min_tl=0, max_tl=8, points=0, categories=["magic"], base_weight=1),
    Skill(name="Экономика", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Эксперт", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Электрик/ТУ", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=6, max_tl=12, points=0, categories=["electronics"], base_weight=2),
    Skill(name="Эротическое искусство", base_attr="DX", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Ювелир/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Яды/ТУ", base_attr="IQ", difficulty="H", tags=["mundane"], min_tl=5, max_tl=12, points=0, categories=["medicine"], base_weight=1),
    Skill(name="Язык жестов", base_attr="IQ", difficulty="E", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Язык тела", base_attr="IQ", difficulty="A", tags=["mundane"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
    Skill(name="Ясный сон", base_attr="Will", difficulty="H", tags=["super"], min_tl=0, max_tl=8, points=0, categories=[], base_weight=1),
]
